### ISSUE TITLE
Python 3.12 bundle on Ubuntu fails to establish connection to lookup server or token generator

### ISSUE THREAD

**Issue by jotelha** [livMatS/dtool-lookup-gui#299]
Logs yield such an error
```
ERROR: Exception in callback ReadTransport._loop_reading(<Future finis...\x00\x00\x00'>)
handle: <GLibHandle ReadTransport._loop_reading(<Future finis...\x00\x00\x00'>)>
Traceback (most recent call last):
  File "asyncio/events.py", line 84, in _run
  File "gbulb/transports.py", line 177, in _loop_reading
  File "gbulb/transports.py", line 127, in _submit_read_data
AttributeError: 'SSLProtocol' object has no attribute 'data_received'. Did you mean: '_eof_received'?
```

**Comment by jotelha** [comment]
Not an issue anymore
