### ISSUE TITLE
Dependency graph construction fails

### ISSUE THREAD

**Issue by jotelha** [livMatS/dtool-lookup-gui#342]
```
2024-10-11 09:21:25,865:asyncio:ERROR: Task exception was never retrieved
future: <Task finished name='Task-78' coro=<MainWindow._compute_dependencies() done, defined at /mnt/dat2/git/dtool/dtool-lookup-gui/dtool_lookup_gui/views/main_window.py:1128> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/mnt/dat2/git/dtool/dtool-lookup-gui/dtool_lookup_gui/views/main_window.py", line 1136, in _compute_dependencies
    await dependency_graph.trace_dependencies(lookup, dataset.uuid, dependency_keys=settings.dependency_keys)
  File "/mnt/dat2/git/dtool/dtool-lookup-gui/dtool_lookup_gui/utils/dependency_graph.py", line 73, in trace_dependencies
    uuid = dataset['uuid']
TypeError: string indices must be integers
```

**Comment by jotelha** [comment]
Fixed
