### ISSUE TITLE
Direct list in GUI stays empty when endpoint holds invalid datasets

### ISSUE THREAD

**Issue by jotelha** [livMatS/dtool-lookup-gui#39]
This occurs with dtool-s3. In particular, a dataset has been partially copied to an s3 endpoint due to non ASCII characters in an item name. As expected, the CLI displays the particular dataset as Proto

```console
$ dtool ls s3://frct-livmats
2021-11-22-hoermann-livmats-demo-videos
  s3://frct-livmats/6d3489a6-c2f7-4dcf-ad4e-38bd4a3de9cb
*2021-10-14-hoermann-rdm-plan-evaluation
  s3://frct-livmats/70d17ce4-52d5-4086-a563-0021dd815500
2021-10-20-hoermann-rdm-discussion
  s3://frct-livmats/b32771f8-3afc-4f57-b4f2-7cca451c9269
2021-11-17-hoermann-livmats-retreat-rdm-intro
  s3://frct-livmats/bbd82391-d21f-4288-b10f-ec3569b8b87f
```

The GUI trows the exception
```
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=True, method=GET, url=https://s3.bwsfs.uni-freiburg.de/frct-livmats/u/jh1130/70d17ce4-52d5-4086-a563-0021dd815500/README.yml, headers={'User-Agent': b'Boto3/1.16.59 Python/3.8.10 Linux/5.11.0-40-generic Botocore/1.19.59 Resource', 'X-Amz-Date': b'20211124T205448Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=LU4DDIGWDX38BMSTFN7H/20211124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=00d662b3b0c686b1fb15616d2a0e250590730adf8db4b584259b655d3c86c3c7'}>
DEBUG:urllib3.connectionpool:https://s3.bwsfs.uni-freiburg.de:443 "GET /frct-livmats/u/jh1130/70d17ce4-52d5-4086-a563-0021dd815500/README.yml HTTP/1.1" 404 258
DEBUG:botocore.parsers:Response headers: {'Date': 'Wed, 24 Nov 2021 20:54:48 GMT', 'Content-Type': 'application/xml', 'Content-Length': '258', 'Connection': 'keep-alive', 'Server': 'StorageGRID/11.4.0.4', 'x-amz-request-id': '1637787288260525', 'x-amz-id-2': '12624338'}
DEBUG:botocore.parsers:Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/frct-livmats/u/jh1130/70d17ce4-52d5-4086-a563-0021dd815500/README.yml</Resource><RequestId>1637787288260525</RequestId></Error>'
DEBUG:botocore.parsers:Response headers: {'Date': 'Wed, 24 Nov 2021 20:54:48 GMT', 'Content-Type': 'application/xml', 'Content-Length': '258', 'Connection': 'keep-alive', 'Server': 'StorageGRID/11.4.0.4', 'x-amz-request-id': '1637787288260525', 'x-amz-id-2': '12624338'}
DEBUG:botocore.parsers:Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/frct-livmats/u/jh1130/70d17ce4-52d5-4086-a563-0021dd815500/README.yml</Resource><RequestId>1637787288260525</RequestId></Error>'
DEBUG:botocore.hooks:Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f67f7d8b4f0>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:botocore.hooks:Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f67f7d8b5b0>>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-79' coro=<SignalHandler._dtool_copy_left_to_right() done, defined at /home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/TransferTab.py:207> exception=NoSuchKey('An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.')>
Traceback (most recent call last):
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/TransferTab.py", line 212, in _dtool_copy_left_to_right
    self.rhs_base_uri_inventory_group.refresh(selected_uri=target_dataset_uri)
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/dtool_gtk.py", line 476, in refresh
    self.populate(*args, **kwargs)
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/dtool_gtk.py", line 416, in populate
    self._dataset_list_model.reindex()
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/models.py", line 198, in reindex
    ds_info = _proto_dataset_info(ds)
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/models.py", line 60, in _proto_dataset_info
    info["readme_content"] = dataset.get_readme_content()
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/dtoolcore/__init__.py", line 452, in get_readme_content
    return self._storage_broker.get_readme_content()
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/dtoolcore/storagebroker.py", line 249, in get_readme_content
    return self.get_text(self.get_readme_key())
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/dtool_s3/storagebroker.py", line 429, in get_text
    response = self.s3resource.Object(
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```
and does not display anything in the list.

**Comment by jotelha** [comment]
For local endpoints, list stays empty if (Proto-) Dataset does not contain README.yml. This is alleviated by https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/76

**Comment by jotelha** [comment]
For s3 endpoints, list stays empty without README.yml as well, but StorageBroker throws a different error, we catch all errors with https://github.com/livMatS/dtool-lookup-gui/pull/104, solved.
