### ISSUE TITLE
ValueError: Namespace GtkSource not available

### ISSUE THREAD

**Issue by jotelha** [livMatS/dtool-lookup-gui#95]
```
Traceback (most recent call last):
  File "dtool_lookup_gui/launcher.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "dtool_lookup_gui/main.py", line 42, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace GtkSource not available
[12523] Failed to execute script 'launcher' due to unhandled exception!
```
when launching relase v0.4.5 linux executable on OpenSuse

```
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0.fake-amd64:desktop-4.0.fake-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0.fake-amd64:graphics-4.0.fake-noarch
Distributor ID: openSUSE
Description:    openSUSE Leap 15.3
Release:    15.3
Codename:   n/a
```

possibly related to pyinstaller warning

```
48204 INFO: Loading module hook 'hook-gi.repository.GtkSource.py' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
48205 INFO: GtkSource version is 4
Traceback (most recent call last):
  File "<string>", line 7, in <module>
gi.repository.GLib.Error: g-irepository-error-quark: Typelib file for namespace 'GtkSource', version '4' not found (0)
48285 ERROR: gi repository 'GIRepository 2.0' not found. Please make sure corresponding package is installed.
```

in automatic build workflow, bundle still builds though.

**Comment by jotelha** [comment]
Solved by https://github.com/livMatS/dtool-lookup-gui/pull/94/commits/dd75f126d19f0a2dae234493f9b54b198eb64afc, 
          gir1.2-gtksource-4 gobject-inspection for gtksourceview-4 was missing in ubuntu packages.
