### ISSUE TITLE
ValueError: Namespace GtkSource not available

### ISSUE THREAD

**Issue by jotelha** [livMatS/dtool-lookup-gui#98]
Tarek reported on OpenSuse,
```
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0.fake-amd64:desktop-4.0.fake-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0.fake-amd64:graphics-4.0.fake-noarch
Distributor ID: openSUSE
Description:    openSUSE Leap 15.3
Release:    15.3
Codename:   n/a
```
failure of launching bundled GUI v0.4.5 with
```
Traceback (most recent call last):
  File "dtool_lookup_gui/launcher.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "dtool_lookup_gui/main.py", line 42, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace GtkSource not available
[12523] Failed to execute script 'launcher' due to unhandled exception!
```

**Comment by jotelha** [comment]
Accicentially reported twice
